spring.datasource.url=jdbc:postgresql://localhost:5432/LinkDatabase
spring.datasource.username=postgres
spring.datasource.password=UrangutanStyle69
spring.jpa.hibernate.ddl-auto=update         



#JPA => Delete all data given rerun on the localserver. 
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect