spring.datasource.url=jdbc:postgresql://localhost:5432/LinkDatabase
spring.datasource.username=postgres
spring.datasource.password=UrangutanStyle69
spring.jpa.hibernate.ddl-auto=update         



#JPA => Delete all data given rerun on the localserver. 

# Motifications regarding this line are required, only regarding the CV we don't want to drop, otherwise we want to drop
spring.jpa.hibernate.ddl-auto=update



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Allow larger uploads for project media.
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=520MB


#CORS Configuration
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

#Uploading the PDF file:
file.upload-dir=upload

